sudo: false

env:
  global:
    secure: UimNDqpXAvtGTLBKAKdq3SPFT8615R/7M7wxtgfyvUOC7LXoqRIcXSXryiXD5CCmRsgATG13qAlu6UY8ve5xCU5xFtLIK0gy8ANyc+ZRZjO9UGVZU9UVswbADvEC+K5RwZTGjCnmfe72dv47NtWW1ZYsH/87WK4dwvGP3fIWNR8=

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.9
    - g++-4.9
    - cmake

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/dynd-python/build

before_install:
- export CC=gcc-4.9
- export CXX=g++-4.9

matrix:
  include:
  - language: C++
    compiler: gcc
    env: Miniconda_OS=Linux
  - language: C++
    compiler: gcc
    env: Miniconda_OS=Linux
  - language: python
    python: 3.5
    compiler: gcc
    install:
      # Use the version of numpy that comes preinstalled.
      - travis_retry pip install --install-option="--no-cython-compile" Cython==0.23
      - python -c "from __future__ import print_function; import numpy; print(numpy.__version__)"
      - mkdir libraries
      - pushd libraries
      - git clone --depth=1 https://github.com/libdynd/libdynd.git
      - popd
      - python setup.py install
  - language: objective-c
    compiler: clang
    osx_image: xcode6.4
    env: Miniconda_OS=MacOSX
    addons:
    before_install:
  - language: objective-c
    compiler: clang
    osx_image: xcode6.4
    env: Miniconda_OS=MacOSX
    addons:
    before_install:
  allow_failures:
    - language: objective-c

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-${Miniconda_OS}-x86_64.sh
  - bash Miniconda3-latest-${Miniconda_OS}-x86_64.sh -b
  - export PATH=$HOME/miniconda3/bin:$PATH
  - conda install --yes conda-build jinja2
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then conda install --yes anaconda-client; fi
  - conda build conda.recipe --channel dynd/channel/dev
  - conda install --yes numpy libdynd --channel dynd/channel/dev
  - conda install $(conda build --output conda.recipe)

script:
  - pushd ..
  - python -c "import dynd; dynd.test(verbosity=2, exit=True)"
  - popd

after_success:
  - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then anaconda --token $ANACONDA_TOKEN upload $(conda build --output conda.recipe) --user dynd --channel dev; fi

notifications:
  email: false
  flowdock: b08b3ba4fb86fa48121e90b5f67ccb75
  on_success: change
  on_failure: always
