sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

matrix:
  include:
    language: python
      cache:
        directories:
          - $HOME/.cache/pip
          - $HOME/dynd-python/build
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
            - llvm-toolchain-precise-3.6
          packages:
            - gcc-4.7
            - g++-4.7
            - cmake
    - language: objective-c
      osx_image: xcode6.4
      env: DYND_FFTW=OFF VERBOSE=1
      python: 2.7
      before_install:
        - export CC=clang
        - export CXX=clang++
        - wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
        - bash Miniconda-latest-MacOSX-x86_64.sh -b
        - export PATH=$HOME/miniconda/bin:$PATH
        - conda install --yes conda-build jinja2
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then conda install --yes anaconda-client; fi
      before_script:
        - export TOKEN=iz-20d586ab-7ed7-4b11-b0c6-d63ac91288b4
      script:
        - conda build conda.recipe
      after_success:
        - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then anaconda -t ${TOKEN} upload $(conda build --output conda.recipe) --user dynd --channel dev; fi
            
#           - llvm-3.6-dev # Required by numba
#           - libedit-dev # Required by numba
  
#    - language: objective-c
 #     osx_image: xcode6.4
  ##    env: DYND_FFTW=OFF VERBOSE=1
    #  python: 2.7
     # before_install:
      #  - export CC=clang
  #      - export CXX=clang++
       # - wget https://repo.continuum.io/miniconda/Miniconda-latest-MacOSX-x86_64.sh
   #     - bash Miniconda-latest-MacOSX-x86_64.sh -b
    #  - export PATH=$HOME/miniconda/bin:$PATH
     #   - conda install --yes conda-build jinja2
    #    - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then conda install --yes anaconda-client; fi
     # before_script:
      #  - export TOKEN=iz-20d586ab-7ed7-4b11-b0c6-d63ac91288b4
 #     script:
  #      - conda build conda.recipe
   #   after_success:
    #    - if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then anaconda -t ${TOKEN} upload $(conda build --output conda.recipe) --user dynd --channel dev; fi


install:
  # Make sure the proper C and C++ compilers are used
  - export CC=gcc-4.7
  - export CXX=g++-4.7
  # Install dependencies
  - travis_retry pip install --install-option="--no-cython-compile" Cython==0.21
  - if [ $TRAVIS_PYTHON_VERSION == 2.6 ]; then travis_retry pip install unittest2; fi
#  - travis_retry pip install enum34 # Required by numba
#  - export LLVM_CONFIG=llvm-config-3.6
#  - travis_retry pip install numba==0.20
  # Put libdynd sources in the right place so they are built with dynd-python.
  - mkdir libraries
  - pushd libraries
  - git clone --depth=1 https://github.com/libdynd/libdynd.git
  - popd
  # Build dynd-python
  - python setup.py install

script:
  - pushd ~
  - python -c 'import dynd; dynd.test(verbosity=2, exit=True)'
  - popd

notifications:
  email: false
  flowdock: "b08b3ba4fb86fa48121e90b5f67ccb75"
  on_success: "change"
  on_failure: "always" # "change"
