sudo: false


matrix:
  include:
    python: "2.6"

#python:
 # - "2.6"
  #- "2.7"
#  - "3.3"


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-4.7
    - g++-4.7
    - cmake
#    - llvm-3.6-dev # Required by numba
#    - libedit-dev # Required by numba

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/dynd-python/build

install:
  # Make sure the proper C and C++ compilers are used
  - export CC=gcc-4.7
  - export CXX=g++-4.7
  # Install dependencies
  - travis_retry pip install --install-option="--no-cython-compile" Cython==0.21
  - if [ $TRAVIS_PYTHON_VERSION == 2.6 ]; then travis_retry pip install unittest2; fi
#  - travis_retry pip install enum34 # Required by numba
#  - export LLVM_CONFIG=llvm-config-3.6
#  - travis_retry pip install numba==0.20
  # Put libdynd sources in the right place so they are built with dynd-python.
  - mkdir libraries
  - pushd libraries
  - git clone --depth=1 https://github.com/libdynd/libdynd.git
  - popd
  # Build dynd-python
  - python setup.py install

script:
  - pushd ~
  - python -c 'import dynd; dynd.test(verbosity=2, exit=True)'
  - popd

notifications:
  email: false
  flowdock: "b08b3ba4fb86fa48121e90b5f67ccb75"
  on_success: "change"
  on_failure: "always" # "change"
