language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

branches:
  only:
    - master

install:
  # For newer cmake
  - sudo add-apt-repository -y ppa:kalakris/cmake
  # For gcc 4.7
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install cmake
  - sudo apt-get -qq install gcc-4.7; sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.7 90; export CC="gcc-4.7"
  - sudo apt-get -qq install g++-4.7; sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.7 90; export CXX="g++-4.7"
  # Install dependencies
  - sudo pip install numpy nose cython
#  - pip install scipy
  # Install libdynd
  - git clone --depth=1 https://github.com/libdynd/libdynd.git
  - mkdir libdynd/build
  - pushd libdynd/build
  - cmake -DDYND_BUILD_TESTS=OFF ..
  - make
  - sudo make install
  - sudo ldconfig
  - popd
  # Build dynd-python
  - sudo python setup.py install
  - popd

script:
  - pushd ~
  - python -c 'import dynd; dynd.test(verbosity=2, exit=True)'
  - popd

notifications:
  email: false
  flowdock: "b08b3ba4fb86fa48121e90b5f67ccb75"
  on_success: "change"
  on_failure: "always" # "change"

