# TODO: How to automatically use the version string
#       produced by the build?
version: 0.6.6.{build}

# branches to build
branches:
  only:
    - master
clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

environment:
  # Operating system (build VM template)
  os: Windows Server 2012

  matrix:
    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"

  install:
    - 'ECHO Filesystem root:'
    - 'dir "C:/"'

    - 'ECHO Installed SDKs:'
    - 'dir "C:/Program Files/Microsoft SDKs/Windows"'

    # Install Python (from the official .msi of http://python.org) and pip when
    # not already installed.
    - "powershell ./appveyor/install.ps1"
  
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

    # Install the build dependencies of the project. If some dependencies
    # contain compiled extensions and are not provided as pre-built wheel
    # packages, pip will build them from source using the MSVC compiler
    # matching the target Python version and architecture
    - "%CMD_IN_ENV% pip install -r dev-requirements.txt"


build_script:
  - python setup.py bdist_wheel

test_script:
  - pip install dist\*.whl
  - pushd C:\
  - python -c "import dynd;dynd.test(exit=True)"
  - popd

artifacts:
  - path: dist\*
