# TODO: How to automatically use the version string
#       produced by the build?
version: 0.6.6.{build}

# branches to build
branches:
  only:
    - master
clone_depth: 1

# Do not build on tags (GitHub only)
skip_tags: true

environment:
  # Operating system (build VM template)
  os: Windows Server 2012

  install:
    - python setup.py bdist_wheel

  matrix:
    - PYTHON: "C:/Python34-x64"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "64"



build_script:
  - python setup.py bdist_wheel

test_script:
  - pip install dist\*.whl
  - pushd C:\
  - python -c "import dynd;dynd.test(exit=True)"
  - popd

artifacts:
  - path: dist\*


#    - ps: ./appveyor/install.ps1
    #- SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
    #- pip install -r dev-requirements.txt
