# Do not build on tags (GitHub only)
skip_tags: true

clone_depth: 1

matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  matrix:
    - PYTHON_ARCH: "x86_64"
    - PYTHON_ARCH: "x86"

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda3-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda
  - conda install conda-build
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { conda install anaconda-client }
  - conda build conda.recipe --channel dynd/channel/dev
