# Do not build on tags (GitHub only)
skip_tags: true

clone_depth: 1

os: Visual Studio 2015

matrix:
  fast_finish: true     # immediately finish build once one of the jobs fails.

environment:
  global:
    appveyor_token:
      secure: GvR4dCHoeYM712VDQYvSuNzFu+rZfo/zdns7xGlFPGOKfFvBmVCXTX6iuHmMpUeP
  matrix:
    - PYTHON_ARCH: "x64"
    - PYTHON_ARCH: "x86"

# Appveyor has installed Miniconda on their VMs. See https://github.com/appveyor/ci/issues/359
build_script:
  - if "%PYTHON_ARCH%" == "x64" (set MINI=C:\Miniconda35-x64) else (set MINI=C:\Miniconda35)
  - SET PATH=%MINI%;%MINI%\Scripts;%MINI%\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda install conda-build
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { conda install -q anaconda-client }
  - conda build -q conda.recipe --channel dynd/channel/dev

on_success:
  # Redirect output from stderr to stdout to avoid having the command for uploading
  # the conda package fail in powershell in spite of a successful upload.
  # This happens when an executable writes to stderr while still executing successfully.
  # See http://stackoverflow.com/a/22615314/1935144
  # See also http://stackoverflow.com/a/2095623/1935144
  # Route command back through cmd to avoid the powershell bug entirely.
  # See https://connect.microsoft.com/PowerShell/feedback/details/645954
  - ps: if(-not $env:APPVEYOR_PULL_REQUEST_NUMBER) { cmd /C anaconda --token $env:appveyor_token upload (conda build --output conda.recipe | select -Last 1) --user dynd --channel dev "2>&1" }
