package:
  name: dynd.nd
  version: 0.7.2

build:
  number: {{environ.get('TRAVIS_BUILD_NUMBER', 0)}}    # [unix]
  number: {{environ.get('APPVEYOR_BUILD_NUMBER', 0)}}  # [win]
  rpaths:
    - lib                                                        # [unix]
    - lib/python{{environ.get('PY_VER')}}/site-packages/dynd.nd  # [unix]
  script_env:
    - CC [linux]
    - CXX [linux]

requirements:
  build:
#    - cmake [unix]
    - python
    - setuptools
    - cython >=0.24
    - numpy
    - libdynd
    # Needed for version tags, not necessary on CI systems since it's already there.
    # Comment it out to avoid the unnecessary download.
    #- git
    # CMake is also needed in general but not necessary on CI systems
    #- cmake
  run:
    - python
    - numpy
    - dynd.ndt
    - libdynd

# Test separately to avoid unsatisfiable package dependencies bug on Win32.
test:
  requires:
    - numba
  commands:
    - python -m dynd.nd.test

about:
  home: http://libdynd.org
  license: BSD
