package:
  name: dynd.nd
  version: 0.7.2

build:
  number: {{environ.get('TRAVIS_BUILD_NUMBER', 0)}}    # [unix]
  number: {{environ.get('APPVEYOR_BUILD_NUMBER', 0)}}  # [win]
  script_env:
    - CC [linux]
    - CXX [linux]

requirements:
  build:
#    - cmake [unix]
    - python
    - setuptools
    - cython >=0.24
    - numpy 1.11.0
    - libdynd
    # Needed for version tags, not necessary on CI systems since it's already there.
    # Comment it out to avoid the unnecessary download.
    #- git
    # CMake is also needed in general but not necessary on CI systems
    #- cmake
  run:
    - python
    - numpy >=1.11.0
    - dynd.ndt
    - libdynd
    - libgcc >=5.2    # [linux]

test:
  requires:
    - numba >=0.25.0
  commands:
    - python -m dynd.nd.test

about:
  home: http://libdynd.org
  license: BSD
