{% set version = "0.7.2" %}

package:
  name: dynd.ndt
  version: {{ version }}

build:
  number: {{environ.get('TRAVIS_BUILD_NUMBER', 0)}}    # [unix]
  number: {{environ.get('APPVEYOR_BUILD_NUMBER', 0)}}  # [win]
  script_env:
    - CC [linux]
    - CXX [linux]

requirements:
  build:
#    - cmake [unix]
    - python           # [unix]
    - python >=3.5     # [win]
    - setuptools
    - cython >=0.24
    - numpy 1.11.0
    - libdynd {{ version }}
    # Needed for version tags, not necessary on CI systems since it's already there.
    # Comment it out to avoid the unnecessary download.
    #- git
    # CMake is also needed in general but not necessary on CI systems
    #- cmake
  run:
    - python          # [unix]
    - python >=3.5    # [win]
    - numpy >=1.11.0
    - libdynd {{ version }}
    - libgcc >=5.2    # [linux]

test:
  requires:
    - numba >=0.25.0
  commands:
    - python -m dynd.ndt.test

about:
  home: http://libdynd.org
  license: BSD
