package:
  name: dynd-python
  version: 0.7.0

build:
  always_include_files:
    - lib/libstdc++.so
    - lib/libstdc++.so.6
    - lib/libstdc++.so.6.0.19
  number: {{environ.get('BINSTAR_BUILD', 1)}}
  rpaths:
    - lib/
    - python2.7/site-packages/dynd/

requirements:
  build:
    - cmake [unix]
    - gcc >=4.8
    - python
    - setuptools
    - cython
    - numpy
    - libdynd
  run:
    - python
    - numpy
    - libdynd

test:
  commands:
    - python -c "import dynd; dynd.test()"

about:
  home: https://github.com/libdynd/dynd-python
  license: BSD


