package:
  name: dynd-python
  version: 0.7.0

build:
  number: {{environ.get('TRAVIS_BUILD_NUMBER', 0)}}
  rpaths:
    - lib/
#    - lib/python2.7/site-packages/dynd/ [py2k]
    - {{site.getsitepackages()[0]}}
  script_env:
    - CC [linux]
    - CXX [linux]

requirements:
  build:
#    - cmake [unix]
    - python
    - setuptools
    - cython
    - numpy
    - libdynd
  run:
    - python
    - numpy
    - libdynd

test:
  commands:
#    - otool -l /opt/anaconda/envs/_test/lib/python2.7/site-packages/dynd/config.so
    - python -c "import dynd; dynd.test(verbosity=2)"

about:
  home: https://github.com/libdynd/dynd-python
  license: BSD


